### ISSUE TITLE
frost-api health check endpoint needed

### ISSUE THREAD

**Issue by WesleyCharlesBlake** [poetapp/frost-api#242]
frost-api needs a health check end point needed in order to be able to enable liveness and readiness probes when deploying to kubernetes.

Desired probes:
```
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
```

What we need on the api :

`GET /health` to return a 200 OK without the need to for an auth token.
